# -*- coding: utf-8 -*-
"""scanner rising point.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L8UnQkwm_7UND_B1EOGzPlEQEK3ADqnq
"""

import os
import datetime
import time
import requests
import logging
import warnings
import re
import pandas as pd
import pandas_ta as ta
import yfinance as yf

# 100% 靜音令與忽略警告通知
logging.getLogger('yfinance').setLevel(logging.CRITICAL)
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=UserWarning)

# 啟用 Pandas 中文字元寬度自動對齊功能
pd.set_option('display.unicode.ambiguous_as_wide', True)
pd.set_option('display.unicode.east_asian_width', True)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# ==========================================
# 0. 設定您的 Telegram 資訊
# ==========================================
TELEGRAM_TOKEN = os.environ.get("TG_TOKEN", "8825844530:AAFGJ30cUvFDyOjreP75nPPtx70-HZZfkT0")
TELEGRAM_CHAT_ID = os.environ.get("TG_CHAT_ID", "5220963669")

def send_tg_msg(msg):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    try:
        requests.post(url, json={"chat_id": TELEGRAM_CHAT_ID, "text": msg, "parse_mode": "HTML"}, timeout=10)
    except Exception as e:
        print(f"❌ Telegram 發送失敗: {e}")

# ==========================================
# 1. 鐵血下載解析
# ==========================================
def get_all_taiwan_stocks_official():
    print("📋 正在從台灣證券編碼官方網頁暴力下載股票清單...")
    stock_dict = {}
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    }
    urls = [
        ("https://isin.twse.com.tw/isin/C_public.jsp?strMode=2", "TW"),
        ("https://isin.twse.com.tw/isin/C_public.jsp?strMode=4", "TWO")
    ]
    for url, m_type in urls:
        try:
            res = requests.get(url, headers=headers, timeout=15)
            res.encoding = 'big5'
            dfs = pd.read_html(res.text)
            df = dfs[0]
            for index, row in df.iterrows():
                cell_text = str(row.iloc[0]).strip()
                match = re.match(r'^(\d{4})\s+(.+)$', cell_text)
                if match:
                    sid = match.group(1)
                    sname = match.group(2).strip()
                    if "特" in sname or "甲" in sname or "乙" in sname: continue

                    # 🛡️ 程式端直接加大牛股過濾名單，杜絕雜訊
                    heavy = [
                        "2330", "2317", "2454", "2308", "2881", "2882", "2886", "2002",
                        "1301", "1303", "1326", "6505", "2834", "5347", "2880", "2891", "2892"
                    ]
                    if sid in heavy: continue

                    yf_code = f"{sid}.{m_type}"
                    stock_dict[yf_code] = {"sid": sid, "sname": sname}
        except Exception as e:
            print(f"❌ 讀取官方網頁失敗 ({m_type}): {e}")
    print(f"📊 成功下載並過濾出 {len(stock_dict)} 檔台灣上市櫃普通股！")
    return stock_dict

# ==========================================
# 2. 鐵血 666 戰法核心邏輯
# ==========================================
def calculate_true_666_strategy(df_60m, df_d, ticker):
    required_cols = ["High", "Low", "Close", "Volume", "Open"]
    if not all(col in df_60m.columns for col in required_cols): return None
    if not "Volume" in df_d.columns: return None
    if len(df_60m) < 65 or len(df_d) < 5: return None

    recent_5d_vol = df_d["Volume"].dropna().tail(5)
    if len(recent_5d_vol) < 5 or recent_5d_vol.mean() < 1000000: return None

    c_ser = df_60m["Close"].squeeze()
    h_ser = df_60m["High"].squeeze()
    l_ser = df_60m["Low"].squeeze()
    v_ser = df_60m["Volume"].squeeze()
    o_ser = df_60m["Open"].squeeze()

    ma60_series = ta.sma(c_ser, length=60)
    if ma60_series is None or len(ma60_series) == 0: return None
    ma60 = ma60_series.iloc[-1]

    kd_df = ta.stoch(high=h_ser, low=l_ser, close=c_ser, k=60, d=3, smooth_k=3)
    if kd_df is None or len(kd_df) < 2: return None
    k_col = [col for col in kd_df.columns if col.startswith("STOCHk")][0]
    d_col = [col for col in kd_df.columns if col.startswith("STOCHd")][0]
    kv = float(kd_df[k_col].iloc[-1])
    dv = float(kd_df[d_col].iloc[-1])
    if kv < 60.0: return None

    macd_df = ta.macd(close=c_ser, fast=12, slow=26, signal=9)
    if macd_df is None or len(macd_df) < 2: return None
    macd_diff = float(macd_df.iloc[-1, 1])

    chg = c_ser.diff()
    su = v_ser.where(chg > 0, 0).rolling(26).sum().iloc[-1]
    sd = v_ser.where(chg < 0, 0).rolling(26).sum().iloc[-1]
    sf = v_ser.where(chg == 0, 0).rolling(26).sum().iloc[-1]
    if pd.isna(su) or pd.isna(sd) or pd.isna(sf): return None
    denom = 1 if (sd + 0.5 * sf) == 0 else (sd + 0.5 * sf)
    vr26 = ((su + 0.5 * sf) / denom) * 100

    bb_df = ta.bbands(close=c_ser, length=20, std=2)
    if bb_df is None or len(bb_df) < 2: return None
    bb_upper = float(bb_df.iloc[-1, 2])
    bb_middle = float(bb_df.iloc[-1, 1])

    c_p = float(c_ser.iloc[-1])
    o_p = float(o_ser.iloc[-1])
    v_p = float(v_ser.iloc[-1])
    v_mean_20h = v_ser.tail(21).head(20).mean()

    if c_p < bb_middle or c_p < ma60: return None
    if v_mean_20h > 0 and v_p < v_mean_20h: return None
    if (c_p - o_p) / o_p * 100 < -0.5: return None

    if kv > dv and macd_diff > 0 and vr26 >= 100.0:
        vol_mult = round(v_p / v_mean_20h, 1) if v_mean_20h > 0 else 1.0
        return {
            "現價": round(c_p, 2), "60MA位置": round(ma60, 2), "布林上軌": round(bb_upper, 2),
            "小時量比數字": vol_mult, "小時量比": f"{vol_mult}倍",
            "K值": round(kv, 1), "D值": round(dv, 1), "MACD柱": round(macd_diff, 3),
            "VR值數字": vr26, "VR值": f"{round(vr26, 1)}%"
        }
    return None

# ==========================================
# 3. 主程式流
# ==========================================
if __name__ == "__main__":
    print("🚀 啟動【台股 666 戰法·網頁暴力下載排程雷達】...")
    stock_map = get_all_taiwan_stocks_official()
    all_yf_codes = list(stock_map.keys())
    total_count = len(all_yf_codes)

    if total_count == 0:
        print("❌ 錯誤：未能成功取得股票清單。")
    else:
        results, tg_msgs = [], []
        chunk_size = 40

        for i in range(0, total_count, chunk_size):
            chunk = all_yf_codes[i:i + chunk_size]
            try:
                data_60m = yf.download(chunk, period="30d", interval="60m", group_by="ticker", progress=False, auto_adjust=False)
                data_d = yf.download(chunk, period="12d", interval="1d", group_by="ticker", progress=False, auto_adjust=False)
            except Exception as e:
                time.sleep(3)
                continue

            for ticker in chunk:
                try:
                    if ticker not in data_60m.columns.get_level_values(0) or ticker not in data_d.columns.get_level_values(0): continue
                    df_stock_60m = data_60m[ticker].dropna(subset=["Close"])
                    df_stock_d = data_d[ticker].dropna(subset=["Close"])
                    if df_stock_60m.empty or df_stock_d.empty: continue

                    df_stock_60m.columns = [c.capitalize() for c in df_stock_60m.columns]
                    df_stock_d.columns = [c.capitalize() for c in df_stock_d.columns]

                    res_strat = calculate_true_666_strategy(df_stock_60m, df_stock_d, ticker)
                    if res_strat:
                        sid = stock_map[ticker]["sid"]
                        sname = stock_map[ticker]["sname"]

                        # 計算進階積分（量比愈高、VR在黃金區間愈好）
                        score = res_strat["小時量比數字"] * 10
                        if 150.0 <= res_strat["VR值數字"] <= 400.0:
                            score += 50  # 黃金能量區加50分
                        elif res_strat["VR值數字"] > 400.0:
                            score -= 30  # 過熱扣30分

                        report = {
                            "代碼": sid, "名稱": sname, "現價": res_strat["現價"],
                            "60MA位置": res_strat["60MA位置"], "布林上軌": res_strat["布林上軌"],
                            "60分K值": res_strat["K值"], "60分D值": res_strat["D值"],
                            "MACD柱": res_strat["MACD柱"], "小時量比": res_strat["小時量比"],
                            "VR值": res_strat["VR值"], "score": score, "量比數字": res_strat["小時量比數字"]
                        }
                        results.append(report)
                except:
                    continue

            print(f"⏳ 雷達進度: {min(i + chunk_size, total_count)} / {total_count} 檔...")
            time.sleep(0.5)

        print("\n" + "=" * 95 + "\n🔊 【鐵血 666 雷達】最終精選股票 (💥前三名已自動套用紅底視覺強化)：\n" + "=" * 95)

        if results:
            df_report = pd.DataFrame(results)
            # 依積分與量比進行頂級飆股排序
            df_report = df_report.sort_values(by=["score", "量比數字"], ascending=False).reset_index(drop=True)

            # 刪除排序輔助用欄位
            df_print = df_report.drop(columns=["score", "量比數字"])

            # 轉換為文字行清單
            lines = df_print.to_string().split('\n')
            header = lines[0]
            print(header) # 列印表頭

            # 從第一行資料開始，前三名加上終端機紅底高亮（\033[41;37m 是紅底白字，\033[0m 是重置）
            for idx, line in enumerate(lines[1:]):
                if idx < 3:
                    print(f"\033[41;37m{line}\033[0m")
                    # 同時把前三名打上星號，讓 Telegram 訊息也認得出來
                    row_data = df_report.iloc[idx]
                    tg_msgs.append(
                        f"🔥 <b>【菁英特攻·前三強】★ {row_data['代碼']} {row_data['名稱']} ★</b>\n"
                        f" 📈 現價: {row_data['現價']} (60MA: {row_data['60MA位置']} | 上軌: {row_data['布林上軌']})\n"
                        f" ⚡ 當前小時量比: <b>{row_data['小時量比']}</b> | VR值: <b>{row_data['VR值']}</b>\n"
                        f" 📊 KD值: K {row_data['60分K值']} > D {row_data['60分D值']} | MACD柱: {row_data['MACD柱']}\n"
                    )
                else:
                    print(line)
                    row_data = df_report.iloc[idx]
                    tg_msgs.append(
                        f"🚨 【標準 666 訊號】{row_data['代碼']} {row_data['名稱']}\n"
                        f" 📈 現價: {row_data['現價']} (量比: {row_data['小時量比']} | VR: {row_data['VR值']})\n"
                    )
        else:
            print("❌ 檢查完畢：目前市場上沒有任何股票符合條件。")
        print("=" * 95 + "\n")

        tz_taiwan = datetime.timezone(datetime.timedelta(hours=8))
        now = datetime.datetime.now(tz_taiwan).strftime("%Y-%m-%d %H:%M")

        # 發送到 Telegram
        out_msg = f"🔔 <b>【台股 666 鐵血精選回報】</b>\n⏰ 時間：{now}\n------------------------\n"
        out_msg += "\n".join(tg_msgs) if tg_msgs else "❌ 目前市場無符合條件標的。"
        send_tg_msg(out_msg)

        print("➔ 鐵血視覺強化版全市場掃描完畢！")