# -*- coding: utf-8 -*-
"""scanner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qo_WTWpPZTHRa8aHjaMk-eF1c9XGVj02
"""

import datetime
import os
import time
import pandas as pd
import pandas_ta as ta
import requests
import yfinance as yf


# ==========================================
# 1. 取得台股上市櫃股票清單（含名稱對應）
# ==========================================
def get_taiwan_stock_list():
    """使用證交所與櫃買中心官方 CSV 開放資料，精準抓取全台股代碼與名稱"""
    stock_list = []
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    }

    # 1. 上市股票清單
    try:
        twse_url = "https://www.twse.com.tw/exchangeReport/STOCK_DAY_ALL?response=open_data"
        res = requests.get(twse_url, headers=headers, timeout=15)
        if res.status_code == 200:
            lines = res.text.split("\n")
            for line in lines:
                parts = line.split('","')
                if len(parts) > 1:
                    stock_id = parts[0].replace('"', "").strip()
                    stock_name = parts[1].replace('"', "").strip()
                    # 嚴格過濾：只留 4 位數純股票
                    if len(stock_id) == 4 and stock_id.isdigit():
                        stock_list.append(
                            {
                                "stock_id": stock_id,
                                "stock_name": stock_name,
                                "market": "tse",
                            }
                        )
    except Exception as e:
        print(f"⚠️ 上市清單下載失敗: {e}")

    # 2. 上櫃股票清單
    try:
        tpex_url = "https://www.tpex.org.tw/openapi/v1/tpex_mainboard_daily_close_quotes"
        res = requests.get(tpex_url, headers=headers, timeout=15)
        if res.status_code == 200:
            data = res.json()
            for item in data:
                stock_id = item.get("SecuritiesCompanyCode", "").strip()
                stock_name = item.get("CompanyName", "").strip()
                if len(stock_id) == 4 and stock_id.isdigit():
                    stock_list.append(
                        {
                            "stock_id": stock_id,
                            "stock_name": stock_name,
                            "market": "otc",
                        }
                    )
    except Exception as e:
        print(f"⚠️ 上櫃清單下載失敗: {e}")

    # 備用防呆機制
    if not stock_list:
        return [
            {"stock_id": "2330", "stock_name": "台積電", "market": "tse"},
            {"stock_id": "2317", "stock_name": "鴻海", "market": "tse"},
            {"stock_id": "2454", "stock_name": "聯發科", "market": "tse"},
            {"stock_id": "8069", "stock_name": "元太", "market": "otc"},
        ]

    # 移除重複項
    seen = set()
    unique_list = []
    for d in stock_list:
        if d["stock_id"] not in seen:
            seen.add(d["stock_id"])
            unique_list.append(d)

    return unique_list


# ==========================================
# 2. 60分鐘線核心運算與篩選
# ==========================================
def scan_60m_stock(stock_item):
    stock_id = stock_item["stock_id"]
    stock_name = stock_item["stock_name"]
    market = stock_item["market"]

    yf_code = f"{stock_id}.TWO" if market == "otc" else f"{stock_id}.TW"
    df = yf.download(tickers=yf_code, period="100d", interval="60m", progress=False)

    if df.empty or len(df) < 80:
        return None

    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [col[0].lower() for col in df.columns]
    else:
        df.columns = [col.lower() for col in df.columns]

    for col in ["close", "high", "low", "volume"]:
        df[col] = df[col].astype(float)

    # ==========================================
    # 防控盤機制：計算最近 5 個交易日的日均成交量
    # ==========================================
    recent_5_days_volume = df["volume"].iloc[-25:].sum()
    avg_daily_volume = recent_5_days_volume / 5 / 1000

    MIN_DAILY_VOLUME = 1000  # 🎯 門檻：5日平均量必須大於 1,000 張
    if avg_daily_volume < MIN_DAILY_VOLUME:
        return None

    # ==========================================
    # 🟢 技術指標計算 (VR, 60MA, KD, MACD)
    # ==========================================
    # 1. VR (26)
    df["change"] = df["close"].diff()
    df["vol_up"] = df["volume"].where(df["change"] > 0, 0)
    df["vol_down"] = df["volume"].where(df["change"] < 0, 0)
    df["vol_flat"] = df["volume"].where(df["change"] == 0, 0)

    sum_up = df["vol_up"].rolling(window=26).sum()
    sum_down = df["vol_down"].rolling(window=26).sum()
    sum_flat = df["vol_flat"].rolling(window=26).sum()
    df["VR_26"] = ((sum_up + 0.5 * sum_flat) / (sum_down + 0.5 * sum_flat)) * 100

    # 2. 60MA
    df["ma_60"] = df["close"].rolling(window=60).mean()

    # 3. KD (60, 3, 3)
    kd_df = ta.stoch(
        high=df["high"], low=df["low"], close=df["close"], k=60, d=3, smooth_k=3
    )
    if kd_df is None or kd_df.empty:
        return None
    df["K_60"] = kd_df["STOCHk_60_3_3"]
    df["D_60"] = kd_df["STOCHd_60_3_3"]

    # 4. MACD (12, 26, 9)
    macd_df = ta.macd(close=df["close"], fast=12, slow=26, signal=9)
    if macd_df is None or macd_df.empty:
        return None
    df["macd_dif"] = macd_df["MACD_12_26_9"]
    df["macd_dea"] = macd_df["MACDs_12_26_9"]
    df["macd_hist"] = macd_df["MACDh_12_26_9"]

    today = df.iloc[-1]
    yesterday = df.iloc[-2]

    # ==========================================
    # 🟢 五合一核心策略嚴格過濾
    # ==========================================
    above_ma60 = today["close"] > today["ma_60"]
    kd_golden_cross = (today["K_60"] > today["D_60"]) and (
        yesterday["K_60"] <= yesterday["D_60"]
    )
    kd_strong_zone = (today["K_60"] > 60) and (today["D_60"] > 60)
    vr_healthy = 140 <= today["VR_26"] <= 300
    macd_bullish = today["macd_dif"] > today["macd_dea"]

    # 所有條件同時交集攔截
    if (
        above_ma60
        and (kd_golden_cross or kd_strong_zone)
        and vr_healthy
        and macd_bullish
    ):
        # 🌟 【時區修正】：自動將 Yahoo 的 UTC 時間轉換為台北時間 (+8 小時)
        if df.index[-1].tzinfo is not None:
            tw_time = df.index[-1].tz_convert("Asia/Taipei")
        else:
            tw_time = df.index[-1] + datetime.timedelta(hours=8)

        time_str = tw_time.strftime("%m/%d %H:%M")

        # 🌟 【輸出格式增強】：加入公司名稱與目前最新收盤價
        return (
            f"🔹 *{stock_id} {stock_name}* | 現價: {round(today['close'],2)} | "
            f"60MA: {round(today['ma_60'],2)} | "
            f"60分K值: {round(today['K_60'],1)} | VR: {round(today['VR_26'],1)}% | "
            f"MACD柱: {round(today['macd_hist'],2)} | "
            f"5日日均量: {int(avg_daily_volume)}張 ({time_str})"
        )
    return None


# ==========================================
# 3. Telegram 發送模組
# ==========================================
def send_to_telegram(message):
    # 🌟 從 GitHub Secrets 安全讀取環境變數
    bot_token = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")

    if not bot_token or not chat_id:
        print("⚠️ 找不到 Telegram 金鑰設定，僅於終端機輸出結果。")
        print(message)
        return

    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    payload = {"chat_id": chat_id, "text": message, "parse_mode": "Markdown"}
    try:
        requests.post(url, json=payload)
    except Exception as e:
        print(f"發送失敗: {e}")


# ==========================================
# 4. 主程式執行流
# ==========================================
if __name__ == "__main__":
    print("🚀 終極完美版雷達（含股票名稱+收盤價+時區優化）啟動...")
    all_stocks = get_taiwan_stock_list()

    print(f"📋 正在精準篩選全台股共 {len(all_stocks)} 檔股票的 60分線數據...")

    results = []
    for stock_item in all_stocks:
        try:
            res = scan_60m_stock(stock_item)
            if res:
                results.append(res)
                print(
                    f"🎯 命中極致嚴選標的: {stock_item['stock_id']} {stock_item['stock_name']}"
                )
            time.sleep(0.05)
        except Exception as e:
            pass

    import requests
    # 🌟 暴力接收：直接讀取 GitHub Actions 灌進來的標準台灣時間
    import os
import datetime

# 1. 徹底抽離，單純用本機最穩定的時間，絕不放進迴圈
current_time_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

# 2. 判斷並組合訊息
if 'results' in locals() and results:
    msg_content = f"📊 *台股 60分線戰法篩選結果 [五合一嚴選版]* ({current_time_str}) :\n\n"
    msg_content += "\n".join(results)
else:
    msg_content = f"ℹ️ *台股 60分線篩選* ({current_time_str}) :\n\n當前無符合 (多頭+量能流動+MACD多方波段) 標的。"

# 3. 發送通知
try:
    send_to_telegram(msg_content)
except Exception as e:
    print(f"Telegram 發送失敗: {e}")